import Header from '@/components/Header'
import './globals.css'

export const metadata = {
  title: 'Investa || Your investing guidline',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang='en'>
      <body>
        <Header />
        {children}
      </body>
    </html>
  )
}
